dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
script: bundle exec rake test
before_script:
  - psql -c 'CREATE DATABASE strong_migrations_test;' -U postgres
  - mysql -e 'CREATE DATABASE strong_migrations_test;'
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
notifications:
  email:
    on_success: never
    on_failure: change
