dist: bionic
language: ruby
script: bundle exec rake test
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - createdb strong_migrations_test
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
    - name: MySQL
      rvm: 2.7
      gemfile: Gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysqladmin create strong_migrations_test
    - name: MariaDB
      rvm: 2.7
      gemfile: Gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: 10.3
      before_script:
        - mysqladmin create strong_migrations_test
        - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost'
        - mysql -u root -e 'GRANT ALL ON *.* TO travis@localhost'
notifications:
  email:
    on_success: never
    on_failure: change
