dist: bionic
language: ruby
rvm: 2.6
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
env:
  -
  - HELPERS=t
script: bundle exec rake test
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - createdb strong_migrations_test
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysqladmin create strong_migrations_test
    - gemfile: test/gemfiles/mysql2.gemfile
      env:
        - ADAPTER=mysql2
        - HELPERS=t
      services:
        - mysql
      before_script:
        - mysqladmin create strong_migrations_test
notifications:
  email:
    on_success: never
    on_failure: change
