dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
script: bundle exec rake test
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE strong_migrations_test;' -U postgres
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysql -e 'CREATE DATABASE strong_migrations_test;'
notifications:
  email:
    on_success: never
    on_failure: change
