dist: bionic
language: ruby
rvm: 2.6
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
script: bundle exec rake test
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - createdb strong_migrations_test
matrix:
  include:
    - name: MySQL
      gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      services:
        - mysql
      before_script:
        - mysqladmin create strong_migrations_test
    - name: MariaDB
      gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: 10.3
      before_script:
        - mysqladmin create strong_migrations_test
        - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost'
        - mysql -u root -e 'GRANT ALL ON *.* TO travis@localhost'
notifications:
  email:
    on_success: never
    on_failure: change
