name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7
          gemfile: Gemfile
        - ruby: 2.6
          gemfile: gemfiles/activerecord52.gemfile
        - ruby: 2.5
          gemfile: gemfiles/activerecord51.gemfile
        - ruby: 2.4
          gemfile: gemfiles/activerecord50.gemfile
        # - ruby: 2.7
        #   gemfile: Gemfile
        #   adapter: mysql2
        #   mysql: true
        # - ruby: 2.7
        #   gemfile: Gemfile
        #   adapter: mysql2
        #   mariadb: true
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle update
    - uses: ankane/setup-postgres@v1
    - run: createdb strong_migrations_test
    - run: cat /etc/postgresql/13/main/pg_hba.conf
    - run: bundle exec rake test
